# Generated by Django 5.1.4 on 2025-02-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('songs', models.JSONField(blank=True, default=list)),
                ('artists', models.JSONField(blank=True, default=list)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
