# Generated by Django 5.1.4 on 2025-02-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0002_remove_users_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
