# Generated by Django 5.1.4 on 2025-02-19 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0003_remove_users_id_alter_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='users',
            name='songs',
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='spotify_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='spotify_app.users')),
            ],
        ),
    ]
