# Generated by Django 5.1.4 on 2025-02-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0004_remove_users_artists_remove_users_songs_artists_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='id',
            new_name='code',
        ),
        migrations.AddField(
            model_name='artists',
            name='code',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artists',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='artists',
            unique_together={('code', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='songs',
            unique_together={('code', 'email')},
        ),
    ]
