# Generated by Django 5.1.4 on 2025-02-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0005_rename_id_songs_code_artists_code_alter_artists_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songs',
            name='code',
            field=models.TextField(),
        ),
    ]
